### ISSUE TITLE
keep other sharer.yaml buttons parameters unchanged when changing one button parameter in a specific page

### ISSUE THREAD

**Issue by nicogreu** [ayozehd/sharer#4]
If in my sharer.yaml file, I have, say, facebook, twitter and pinterest enabled:
```
buttons:
    facebook:
        enabled: true
        icon: facebook
    twitter:
        enabled: true
        icon: twitter
    pinterest:
        enabled: true
        icon: pinterest

```
And then in the yaml of a specific page I want to provide the image to share on pinterest:

```
---
sharer:
    buttons:
        pinterest:
             image: http://pathToMyImage.jpg
---
```

It seems the "buttons:" reinitiates all the buttons option values of sharer.yaml and so nothing shows up unless I re-enter those options in the yaml of this specific page:

```
---
sharer:
    buttons:
        facebook:
            enabled: true
            icon: facebook
        twitter:
            enabled: true
            icon: twitter
        pinterest:
            enabled: true
            icon: pinterest
            image: http://pathToMyImage.jpg
---

```
Is there a way to enter specific button option in a page while keeping the default other options from the sharer.yaml file?
